routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\AdminLoginMiddleware;
use App\Http\Controllers\Administrator\PoController;
use App\Http\Controllers\Administrator\LogController;
use App\Http\Controllers\Administrator\RoleController;
use App\Http\Controllers\Administrator\BuyerController;
use App\Http\Controllers\Administrator\ChartController;
use App\Http\Controllers\Administrator\DailyPoController;
use App\Http\Controllers\Administrator\PoFixedController;
use App\Http\Controllers\Administrator\ProfileController;
use App\Http\Controllers\Administrator\DashboardController;
use App\Http\Controllers\Administrator\UserAdminController;
use App\Http\Controllers\Administrator\PermissionController;
use App\Http\Controllers\Administrator\AdminLogableController;
use App\Http\Controllers\Administrator\NotificationController;
use App\Http\Controllers\Administrator\PublicStorageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect()->route('administrator.login');
});

Route::group([
    'prefix' => config('admin.prefix', 'administrator'),
    'as' => 'administrator.',
], function () {

    Route::group([
        'namespace' => 'App\Http\Controllers\Administrator',
    ], function () {
        Auth::routes(['register' => false]);
    });

    Route::group([
        'middleware' => [AdminLoginMiddleware::class],
    ], function () {
        Route::resource('/storage', PublicStorageController::class)->only(['index']);

        Route::resource('/', DashboardController::class)->only(['index']);
        Route::resource('/notification', NotificationController::class)->only(['index', 'show', 'store']);
        Route::resource('/profile', ProfileController::class)->only(['index', 'store']);

        Route::resource('/buyer', BuyerController::class);
        Route::resource('/po', PoController::class);
        Route::resource('/fixed-po', PoFixedController::class);
        Route::resource('/daily-po', DailyPoController::class);
        Route::get('/daily-po/find-date/{date?}', [DailyPoController::class, 'showByDate']);

        Route::get('/chart', [ChartController::class, 'index'])->name('chart.index');
        Route::get('/chart/{date?}', [ChartController::class, 'index'])->name('chart.by_date');
        Route::get('/chart/data/{date?}', [ChartController::class, 'getChart'])->name('chart.data');

        Route::get('/chart/set-silent-alarm/{time?}', [ChartController::class, 'setSilentAlarmTime'])->name('chart.set-silent-alarm-time');

        Route::group(['as' => 'account.', 'prefix' => 'account'], function () {
            Route::resource('/admin', UserAdminController::class);
        });

        Route::group(['as' => 'system.', 'prefix' => 'system'], function () {
            Route::resource('/log', LogController::class)->only(['index']);
            Route::resource('/activity', AdminLogableController::class)->only(['index', 'destroy']);
        });

        Route::group(['as' => 'access.', 'prefix' => 'access'], function () {
            Route::resource('/role', RoleController::class);
            Route::resource('/permission', PermissionController::class)->only(['index', 'show', 'update']);
        });

    });
});

app/Http/Controllers/Administrator/AdminLogableController.php
<?php

namespace App\Http\Controllers\Administrator;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\AdminLogable;
use App\DataTables\AdminLogableDatatables;

class AdminLogableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {

        if(in_array(env('APP_ENV', 'local'), ['local'])) {
            session()->flash('warning', [
                'Add this trait <code>App\Models\AdminLogable</code> to all the Models you want to monitor'
            ]);
        }

        return AdminLogableDatatables::view();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $life = config('admin.log_activity_life', 7);
        $data = AdminLogable::where('created_at', '<', now()->addDays('-' . $life)->format('Y-m-d h:i:s'));
        $count = $data->count();
        $data->delete();

        if($count > 0) {
            session()->flash('success', [
                $count . ' has been deleted'
            ]);
        } else {
            session()->flash('success', [
                'No data available'
            ]);
        }


        return redirect()->back();
    }
}

app/Http/Controllers/Administrator/BuyerController.php
<?php

namespace App\Http\Controllers\Administrator;

use Illuminate\Http\Request;
use App\Exceptions\AdminException;
use App\DataTables\BuyerDatatables;
use App\Http\Controllers\Controller;
use App\Repositories\BuyerRepository;

class BuyerController extends Controller
{

    protected $repository;

    public function __construct(BuyerRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        admin()->allow('administrator.buyer.index');

        return BuyerDatatables::view();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        admin()->allow('administrator.buyer.create');

        return view('administrator.buyer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        admin()->allow('administrator.buyer.create');

        $request->validate([
            'name' => ['required'],
            'target' => ['required', 'min:1', 'max:99'],
            'usl' => ['required', 'min:1', 'max:99'],
            'lsl' => ['required', 'min:1', 'max:99'],
        ]);

        try {

            $request->merge(['created_by' => auth()->id()]);

            $this->repository->createBuyer($request);
            session()->flash('success', [
                'Buyer has been created sucessfully',
            ]);
            return redirect()->back();
        } catch (AdminException $e) {
            return redirect()->back()->withErrors([
                $e->getMessage(),
            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $buyer = $this->repository->getModel()->findOrFail($id);
        return response()->json($buyer);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        admin()->allow('administrator.buyer.update');

        $data['buyer'] = $this->repository->getModel()->findOrFail($id);
        return view('administrator.buyer.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        admin()->allow('administrator.buyer.update');

        $request->validate([
            'name' => ['required'],
            'target' => ['required', 'min:1', 'max:99'],
            'usl' => ['required', 'min:1', 'max:99'],
            'lsl' => ['required', 'min:1', 'max:99'],
        ]);

        try {
            $request->merge(['updated_by' => auth()->id()]);

            $this->repository->updateBuyer($request, $id);
            session()->flash('success', [
                'Update has been sucessfully',
            ]);
            return redirect()->back();
        } catch (AdminException $e) {
            return redirect()->back()->withErrors([
                $e->getMessage(),
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        admin()->allow('administrator.buyer.destroy');

        try {
            $this->repository->getModel()->findOrFail($id)->delete();
            session()->flash('success', [
                'Delete has been sucessfully',
            ]);
            return redirect()->back();
        } catch (AdminException $e) {
            return redirect()->back()->withErrors([
                $e->getMessage(),
            ]);
        }
    }
}

app/Http/Controllers/Administrator/ChartController.php
<?php

namespace App\Http\Controllers\Administrator;

use Carbon\Carbon;
use App\Repositories\PoRepository;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;

class ChartController extends Controller
{

    protected $repository;

    public function __construct(PoRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(string $date = 'today')
    {
        if ($date = 'today') {
            $date = date('Y-m-d');
        }

        $data = ['date' => $date];

        return view('administrator.chart.real-po', $data);
    }

    /**
     * Display a json of the resource po by date for chart.
     *
     * @param string $date
     * @return \Illuminate\Http\Response
     */
    public function getChart(string $date)
    {
        $date_params = date('Y-m-d', strtotime($date));
        /* TODO: Get Date Range For Chart Data And Collect That */
        $date_range = getDateBetweenParams($date_params);
        $listPo = $this->repository->chartByDateRange($date_range);

        $collectPo = collect($listPo);

        /* TODO: Po (A) and Po (B) Min Max Value */
        $po_a_min = $collectPo->where('po_a', '!=', 0)->min('po_a');
        $po_a_max = $collectPo->where('po_a', '!=', 0)->max('po_a');

        $po_b_min = $collectPo->where('po_b', '!=', 0)->min('po_b');
        $po_b_max = $collectPo->where('po_b', '!=', 0)->max('po_b');

        /* TODO: Po (A) and Po (B) Temporary Min Max Value */
        $po_a_min_temp = $collectPo->where('po_a_temp', '!=', 0)->min('po_a_temp');
        $po_a_max_temp = $collectPo->where('po_a_temp', '!=', 0)->max('po_a_temp');

        $po_b_min_temp = $collectPo->where('po_b_temp', '!=', 0)->min('po_b_temp');
        $po_b_max_temp = $collectPo->where('po_b_temp', '!=', 0)->max('po_b_temp');

        $min_lsl = $collectPo->where('lsl', '!=', 0)->min('lsl');

        /* TODO: Initial po & po_temp data */
        $po = [];
        $po_temp = [];

        foreach ($listPo as $key => $data) {
            /* TODO: Po Report By Hours */
            $po[$data['report_time']] = [
                date('H:i', strtotime($data['report_time'])),
                $data['po_a']==0 ? null : $data['po_a'],
                $data['po_b']==0 ? null : $data['po_b'],
                $data['target']==0 ? null : $data['target'],
                $data['ucl1']==0 ? null : $data['ucl1'],
                $data['lcl1']==0 ? null : $data['lcl1'],
                $data['usl']==0 ? null : $data['usl'],
                $data['lsl']==0 ? null : $data['lsl'],
            ];

            /* TODO: Po Temporary Report By Hours */
            $po_temp[$data['report_time']] = [
                date('H:i', strtotime($data['report_time'])),
                $data['po_a_temp']==0 ? null : $data['po_a_temp'],
                $data['po_b_temp']==0 ? null : $data['po_b_temp'],
                $data['target']==0 ? null : $data['target'],
                $data['ucl1']==0 ? null : $data['ucl1'],
                $data['lcl2']==0 ? null : $data['lcl2'],
                $data['usl']==0 ? null : $data['usl'],
                $data['lsl']==0 ? null : $data['lsl'],
            ];
        }

        /* TODO: Initial Po & Po Temporary Current */
        $po_current = null;
        $po_current_temp = null;

        $current_time = getCurrentTime();
        if (array_key_exists($current_time, $po)) {
            /* TODO: Po & Po Temporary Currently */
            $po_current = $po[$current_time];
            $po_current_temp = $po_temp[$current_time];
        }

        /* TODO: Initial Array List Time For Chart */
        $chart_data = [];
        $chart_data_temp = [];

        $last_target = $last_ucl_a = $last_lcl_b = $usl = $lsl = null;
        $last_target_temp = $last_ucl_a_temp = $last_lcl_b_temp = $usl_temp = $lsl_temp = null;

        /* TODO: Each Int From 0 to 24 For Get Chart Data By Hours */
        foreach (range(intval('00:00:00'), intval('24:00:00')) as $time) {

            /* TODO: Initial date range when time is between 20:30-23:30 */
            $date_a = $date_range[1]->format('Y-m-d ') . date("H:00:00", mktime($time + 20));
            $date_b = $date_range[1]->format('Y-m-d ') . date("H:30:00", mktime($time + 20));

            /* TODO: Initial date range when time is not between 20:30-23:30 */
            if ($time <= 3) {
                $date_a = $date_range[0]->format('Y-m-d ') . date("H:00:00", mktime($time + 20));
                $date_b = $date_range[0]->format('Y-m-d ') . date("H:30:00", mktime($time + 20));
            }

            if (array_key_exists($date_a, $po)) {
                $chart_data[] = $po[$date_a];
                $last_target = $po[$date_a][3];
                $last_ucl_a = $po[$date_a][4];
                $last_lcl_b = $po[$date_a][5];
                $usl = $po[$date_a][6];
                $lsl = $po[$date_a][7];
            } else {
                $chart_data[] = [date('H:i', strtotime($date_a)), null, null, $last_target, $last_ucl_a, $last_lcl_b, $usl, $lsl];
            }

            if (array_key_exists($date_a, $po_temp)) {
                $chart_data_temp[] = $po_temp[$date_a];
                $last_target_temp = $po_temp[$date_a][3];
                $last_ucl_a_temp = $po_temp[$date_a][4];
                $last_lcl_b_temp = $po_temp[$date_a][5];
                $usl_temp = $po_temp[$date_a][6];
                $lsl_temp = $po_temp[$date_a][7];
            } else {
                $chart_data_temp[] = [date('H:i', strtotime($date_a)), null, null, $last_target_temp, $last_ucl_a_temp, $last_lcl_b_temp, $usl_temp, $lsl_temp];
            }

            if (array_key_exists($date_b, $po)) {
                $chart_data[] = $po[$date_b];
                $last_target = $po[$date_b][3];
                $last_ucl_a = $po[$date_b][4];
                $last_lcl_b = $po[$date_b][5];
                $usl = $po[$date_b][6];
                $lsl = $po[$date_b][7];

            } else {
                $chart_data[] = [date('H:i', strtotime($date_b)), null, null, $last_target, $last_ucl_a, $last_lcl_b, $usl, $lsl];
            }

            if (array_key_exists($date_b, $po_temp)) {
                $chart_data_temp[] = $po_temp[$date_b];
                $last_target_temp = $po_temp[$date_b][3];
                $last_ucl_a_temp = $po_temp[$date_b][4];
                $last_lcl_b_temp = $po_temp[$date_b][5];
                $usl_temp = $po_temp[$date_b][6];
                $lsl_temp = $po_temp[$date_b][7];
            } else {
                $chart_data_temp[] = [date('H:i', strtotime($date_b)), null, null, $last_target_temp, $last_ucl_a_temp, $last_lcl_b_temp, $usl_temp, $lsl_temp];
            }
        }

        /* Remove Last Array */
        array_pop($chart_data);
        array_pop($chart_data_temp);

        $silent_alarm_time = Cache::get('silent_alarm_time', 'Silent Alarm Time Not Exist!');

        $collection_po = collect([$po_a_max, $po_b_max, $po_a_min, $po_b_min, $lsl, $min_lsl]);
        $usl = $collection_po->max();
        $lsl = $collection_po->min();

        $collection_po_temp = collect([$po_a_max_temp, $po_b_max_temp, $po_a_min_temp, $po_b_min_temp, $lsl_temp, $min_lsl]);
        $usl_temp = $collection_po_temp->max();
        $lsl_temp = $collection_po_temp->min();

        return response()->json([
            'date' => $date_range,
            'silent_alarm_time' => $silent_alarm_time,

            'max_y' => ($usl + 1),
            'min_y' => ($lsl - 1),
            'current' => $po_current,
            'chart_data' => $chart_data,

            'max_y_temp' => ($usl_temp + 1),
            'min_y_temp' => ($lsl_temp - 1),
            'current_temp' => $po_current_temp,
            'chart_data_temp' => $chart_data_temp,

        ]);

    }

    /**
     * Set Silent Alarm With Cache Laravel.
     *
     * @return \Illuminate\Http\Response
     */
    public function setSilentAlarmTime(string $time)
    {
        Cache::put('silent_alarm_time', $time, now()->addMinutes(60));

        return response()->json(['message' => "Silent Alarm At {$time} Done!"]);
    }
}

resources/views/administrator/daily-po/index.blade.php
<x-template-layout>
    <x-slot name="title">Daily Po</x-slot>

    <x-slot name="styles">
        <style>
            .table td,
            .table th {
                vertical-align: middle;
            }

            .table-mini td {
                padding: .1rem;
            }

            .form-control {
                text-align: center;
                display: block;
                width: 100%;
                height: calc(1.6em + .75rem + 2px);
                padding: .375rem .75rem;
                font-size: 1.1rem;
                font-weight: 400;
                line-height: 1.6;
                color: #495057;
                background-color: #fff;
                background-clip: padding-box;
                border: 1px solid transparent;
                border-radius: .25rem;
                transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
            }

            .blinking {
                animation: blinkingText 1.2s infinite;
            }

            @keyframes blinkingText {
                0% {
                    color: #000;
                }

                49% {
                    color: #000;
                }

                60% {
                    color: transparent;
                }

                99% {
                    color: transparent;
                }

                100% {
                    color: #000;
                }
            }

        </style>
    </x-slot>
    <div class="row">
        <x-template-card class="col-12">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <div class="row">
                    <div class="col-6 table-responsive text-center mt-4">
                        <table id="table-po-temp" class="table table-sm table-hover table-bordered rotate-table-grid" style="font-size:32pt; line-height:1.05">
                            <thead>
                                <tr>
                                    <th colspan="2" class="bg-warning" id="current-time">JAM --:--</th>
                                </tr>
                                <tr class="bg-success">
                                    <th>DRYER A</th>
                                    <th>DRYER B</th>
                                </tr>
                            </thead>
                            <tbody height="438px">
                                <tr class="bg-default" style="font-size:188pt; line-height:1.05">
                                    <td id="current-po-a">-</td>
                                    <td id="current-po-b">-</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-6 table-responsive text-center mt-4">
                        <form action="{{ route('administrator.daily-po.store') }}" method="post">
                            @csrf
                            <table id="table-po-temp" class="table table-mini table-hover table-bordered rotate-table-grid" style="font-size:22pt; line-height:1.05">
                                <thead>
                                    <tr>
                                        <th colspan="3" class="bg-warning" id="current-date">PROD 27 November 2021</th>
                                    </tr>
                                    <tr class="bg-success">
                                        <th width="30%">SHIFT</th>
                                        <th width="35%">MALAM</th>
                                        <th width="35%">PAGI</th>
                                    </tr>

                                </thead>
                                <tbody style="font-size:0.8em; line-height:1.05;">
                                    <tr class="bg-success">
                                        <td>PROD</td>
                                        <td>
                                            <input type="text" class="form-control bg-success" name="cooper_a" id="cooper_a" placeholder="">
                                        </td>
                                        <td>
                                            <input type="text" class="form-control bg-success" name="cooper_b" id="cooper_b" placeholder="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>BLOK</td>
                                        <td>
                                            <input type="hidden" name="date_report" id="date_report">
                                            <input type="text" class="form-control" name="block_a" id="block_a" placeholder="">
                                        </td>
                                        <td>
                                            <input type="text" class="form-control" name="block_b" id="block_b" placeholder="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>DRC</td>
                                        <td>
                                            <input type="text" class="form-control" name="drc_a" id="drc_a" placeholder="">
                                        </td>
                                        <td>
                                            <input type="text" class="form-control" name="drc_b" id="drc_b" placeholder="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>PO</td>
                                        <td>
                                            <input type="text" class="form-control" name="po_a" id="po_a" placeholder="">
                                        </td>
                                        <td>
                                            <input type="text" class="form-control" name="po_b" id="po_b" placeholder="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>PRI</td>
                                        <td>
                                            <input type="text" class="form-control" name="pri_a" id="pri_a" placeholder="">
                                        </td>
                                        <td>
                                            <input type="text" class="form-control" name="pri_b" id="pri_b" placeholder="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>UMUR JEMUR</td>
                                        <td>
                                            <input type="text" class="form-control" name="umur_jemur_a" id="umur_jemur_a" placeholder="">
                                        </td>
                                        <td>
                                            <input type="text" class="form-control" name="umur_jemur_b" id="umur_jemur_b" placeholder="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>KAMAR</td>
                                        <td>
                                            <input type="text" class="form-control" name="kamar_a" id="kamar_a" placeholder="">
                                        </td>
                                        <td>
                                            <input type="text" class="form-control" name="kamar_b" id="kamar_b" placeholder="">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>TARGET / RANGE</td>
                                        <td>
                                            <input type="text" class="form-control" name="target_a" id="target_a" placeholder="">
                                        </td>
                                        <td>
                                            <input type="text" class="form-control" name="target_b" id="target_b" placeholder="">
                                        </td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="3">
                                            <button type="submit" id="submit-data" class="btn btn-primary">Submit Data</button>
                                        </th>
                                    </tr>
                                </tfoot>
                            </table>
                        </form>
                    </div>

                    <div class="col-12 table-responsive mt-4">
                        <table id="table-po-temp" class="table table-sm table-hover table-bordered table-striped rotate-table-grid" style="font-size:9pt; line-height:1.05">
                            <thead id="render-thead-temp"></thead>
                            <tbody id="render-tbody-temp"></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </x-template-card>
    </div>

    <x-slot name="scripts">
        <script type="text/javascript" src="{{ asset('js/admin/daily-po.js') }}"></script>
    </x-slot>
</x-template-layout>